/**
 * All narration text lives here so it can be edited without touching scene code.
 * Keep sentences short. One idea per paragraph. No formula before the picture that explains it.
 */

export const site = {
  title: "Lattice",
  tagline: "The math that is replacing the internet's locks.",
  intro: [
    "How your phone keeps secrets, why quantum computers put that in danger, and the puzzle about dots that will keep us safe.",
    "Told step by step, with moving pictures. No maths needed. Just scroll.",
  ],
  scrollHint: "Scroll to begin",
};

/**
 * Scroll-story chapters: each step is one or two short sentences; the picture changes as each step
 * scrolls into the middle of the screen. Alex sends, Sam receives, Eve snoops — in every chapter.
 */
export const sound = {
  group: "Sound",
  voice: "Voice",
  effects: "Sound effects",
  on: "on",
  off: "off",
  voiceMissing: "The voice recordings haven’t been added yet.",
};

export const chapter0 = {
  kicker: "Chapter 0",
  title: "The problem",
  steps: [
    "Meet Alex and Sam. Alex wants to send Sam a message: “meet at 5”.",
    "The message doesn’t fly straight to Sam. It hops through lots of computers on the way: Wi-Fi boxes, routers, servers.",
    "Meet Eve. Eve runs one of those computers. Every message that passes through, she can read and quietly copy.",
    "So Alex locks the message before sending it. Now Eve only sees scrambled junk.",
    "But there’s a catch. To open the lock, Sam needs the key. If Alex sends the key, Eve copies the key too. Alex and Sam have never met. How can they share a key?",
    "Here is the clever answer. Sam gets a special padlock. It comes with just one key, and Sam keeps that key at home. The key never travels.",
    "Sam sends the padlock, open, to Alex. Eve copies it on the way. That’s fine: this padlock can only lock things. It can never unlock anything.",
    "Alex puts the message in a box and clicks Sam’s padlock shut. Click! Now nobody can open it without Sam’s key. Not even Alex.",
    "The locked box travels to Sam. Eve copies it too, but she has no key, so her copy stays shut. Sam uses the key, and the box opens.",
    "That is what the little padlock next to a website’s address means. Your phone and the website just did this dance, in a blink.",
    "Today’s padlocks are built on a number puzzle. Multiplying two numbers is easy. Going backwards, finding which two numbers were multiplied, is hard. Real padlocks use numbers hundreds of digits long.",
    "But a big enough quantum computer can go backwards fast. When those machines arrive, today’s padlocks pop open. And Eve has been saving copies all along.",
    "So the world is switching to a new padlock, built on a different puzzle. Nobody knows how to crack it, not even with a quantum computer. It is a puzzle about dots.",
  ],
  labels: {
    alex: "Alex",
    sam: "Sam",
    eve: "Eve",
    message: "meet at 5",
    scrambled: "k#8!q@z",
    noKey: "no key!",
    stays: "stays with Sam",
    onlyLocks: "can only lock ✓",
    click: "click!",
    how: "?",
    url: "shop.example",
    multiply: "37 × 53",
    product: "1,961",
    easy: "easy: one quick sum",
    hard: "hard: guess… guess… guess…",
    tries: ["2 × ?", "3 × ?", "7 × ?", "11 × ?", "13 × ?", "17 × ?", "19 × ?", "23 × ?", "29 × ?", "31 × ?", "37 × 53 ✓"],
    quantum: "quantum computer",
    fast: "fast!",
    dots: "a new puzzle",
    aria: "Alex sends Sam a message across the internet while Eve listens",
  },
};

export const chapter1 = {
  kicker: "Chapter 1",
  title: "A grid of dots",
  steps: [
    "Start with one arrow. Call it A.",
    "Take a step along A. Then another, and another. Backwards too. Every stop leaves a dot. You get a row of dots.",
    "Now add a second arrow, B, pointing a different way.",
    "Slide the whole row along B, again and again, up and down. The rows stack up into a grid.",
    "This grid of dots is called a lattice. The two arrows that build it are called its basis.",
    "Every dot has an address. Start at the centre dot. Walk 3 steps along A, then 2 steps along B. You land exactly on a dot. Its address is (3, 2).",
    "Steps can go backwards too. Walk 1 step back along A, then 2 steps along B. You land on the dot (−1, 2).",
    "But no half steps are allowed. Half a step along A lands between the dots, on no dot at all. Every dot is a whole number of steps away.",
    "Now drop a ball anywhere between the dots. The question: which dot is closest to the ball?",
    "Measure from the ball to the dots around it. The shortest line wins.",
    "In a flat grid you can almost see the answer. Remember this question: “which dot is closest?” It is the puzzle behind the new padlock, and it gets very hard when the grid goes in hundreds of directions instead of two.",
  ],
  labels: {
    a: "A",
    b: "B",
    lattice: "lattice",
    basis: "basis",
    start: "start",
    counter: "A steps: {a}    B steps: {b}",
    address: "({a}, {b})",
    half: "½ step: no dot here",
    closest: "closest",
    aria: "Building a grid of dots from two arrows, then finding the dot closest to a ball",
  },
};

export const chapter2 = {
  kicker: "Chapter 2",
  title: "Two ways to walk",
  steps: [
    "Here is a new grid. It is built by two short, square arrows. Let’s call them the green arrows.",
    "Now meet a different pair: two long, crooked arrows. Call them the red arrows.",
    "Watch the dots while we swap the green arrows for the red ones. Not a single dot moves. The red arrows build exactly the same grid.",
    "Take this dot. With the green arrows the walk is short: 1 step along the first arrow, 1 step along the second.",
    "Now reach the same dot with the red arrows: 1 step backwards along the first, then 2 along the second. A long zig-zag, far out and back, to the same dot.",
    "Now drop a ball. To find the closest dot, there is a simple method: walk with your two arrows, rounding to whole steps. With the green arrows, it lands on the closest dot.",
    "With the red arrows, the very same method lands on the wrong dot, far from the ball. The real closest dot was right next to it.",
    "This is the secret behind the new padlock. Sam keeps the green arrows private. Everyone, even Eve, gets the red arrows. Same grid, but only Sam can find the closest dot easily.",
  ],
  labels: {
    green: "green arrows",
    red: "red arrows",
    same: "same dots",
    short: "short walk",
    long: "long walk",
    right: "closest dot ✓",
    wrong: "wrong dot ✗",
    real: "the real closest dot",
    sam: "Sam",
    eve: "Eve",
    private: "private",
    public: "public",
    aria: "The same grid built by a short square pair of arrows and by a long crooked pair",
  },
};

export const chapter3 = {
  kicker: "Chapter 3",
  title: "Add a shake",
  steps: [
    "Now Alex sends Sam a secret bit: a 0 or a 1. Alex only has the red arrows, but that’s enough to find dots on Sam’s grid.",
    "To send a 0, Alex picks any dot and puts the ball right on it.",
    "To send a 1, Alex puts the ball exactly halfway between two dots.",
    "But there’s a problem. Eve can read that too. On a dot means 0, exactly halfway means 1. No secret needed.",
    "So before sending, Alex gives the ball a small random shake. Now it sits near its spot, but not exactly on it.",
    "Sam rounds the shaken ball with the green arrows and looks at what is left over. Almost nothing means 0. About half a step means 1. Sam reads it right.",
    "Eve rounds with the red arrows. Her long, crooked arrows take her to the wrong neighbouring dot, so the leftover she measures is nonsense. Her answer is just a guess.",
    "Send ten bits. Sam reads all ten. Eve gets about half: no better than flipping a coin.",
    "But too much shake and even Sam gets lost. Real padlocks use a shake that is just right. This trick is called Learning With Errors, and it is the heart of the new padlock.",
  ],
  labels: {
    zero: "0",
    one: "1",
    halfway: "halfway",
    eveReads: "Eve reads {b} ✓",
    samReads: "Sam reads {b}",
    eveGuess: "Eve reads {b}",
    shake: "shake",
    leftover: "leftover",
    sam: "Sam",
    eve: "Eve",
    score: "{r} of {n} right",
    tooMuch: "too much shake",
    aria: "Sending one secret bit as a ball on a grid, with a small shake",
  },
};

export const chapter4 = {
  kicker: "Chapter 4",
  title: "Why bigger grids win",
  steps: [
    "Eve has a weapon: a famous method called LLL. It takes crooked red arrows and tidies them, one move at a time.",
    "Move one: shorten an arrow by taking the other one away from it. Move two: swap the arrows if the shorter one is second. Repeat until nothing changes.",
    "In a flat grid, Eve needs only a few moves to get short, square arrows. With those, she can read Sam’s messages. A flat grid is not safe.",
    "So real padlocks don’t use a flat grid. They use grids that go in hundreds of directions at once. We can’t draw that, but we can test it.",
    "This chart runs Eve’s weapon on grids with more and more directions: 2, 4, 6… up to 40. Each bar shows how often she found the secret.",
    "With a few directions, Eve wins almost every time. Past about 30 directions she almost never does. Her weapon still finishes, but its arrows are no longer good enough.",
    "Real padlocks use 500 to 1,000 directions. Far beyond anything Eve can tidy.",
    "What about quantum computers? They are brilliant at one thing: finding hidden repeating patterns. That’s how they crack today’s number puzzle. A grid in hundreds of directions has no such pattern, so they barely help.",
  ],
  labels: {
    lll: "LLL",
    move: "move {n}",
    shorten: "shorten",
    swap: "swap",
    done: "tidy ✓",
    directions: "directions",
    wins: "Eve finds the secret",
    safe: "safe",
    real: "real padlocks: 500–1,000 →",
    pattern: "no pattern to find",
    quantum: "quantum computer",
    eve: "Eve",
    message: "meet at 5",
    aria: "Eve's LLL weapon tidying crooked arrows, and a chart of how often it works as the grid gets more directions",
  },
};

export const chapter5 = {
  kicker: "Chapter 5",
  title: "The real thing",
  steps: [
    "Now the real padlock, shrunk until every number fits on screen. It is called ML-KEM, and your browser has used it since 2024.",
    "First, the numbers live on a clock with 97 hours. Go past 96 and you wrap back round to 0, just like a clock going past 12.",
    "Sam makes keys. Sam’s secret is a short list of tiny numbers: −1, 0 or 1. These play the part of the green arrows.",
    "Sam mixes the secret into a big public jumble of numbers, then adds a small shake. The result is Sam’s public padlock. Anyone can have it.",
    "Alex picks a random secret key: eight 0s and 1s. Each 1 is pushed halfway round the clock, to 49. Then Alex mixes in Sam’s padlock, adds a fresh shake, and sends the result.",
    "Eve sees the jumble, the padlock and Alex’s message. Without Sam’s secret, it is just a mess of numbers.",
    "Sam uses the secret to cancel the jumble. On the clock, the eight numbers slide into two groups: near 0 means 0, near the far side means 1.",
    "Now Alex and Sam share the same secret key, and nobody else has it. They use it to lock their real messages. The same trick as the grid, done with numbers.",
  ],
  labels: {
    hours: "97-hour clock",
    wrap: "96 → 0",
    secret: "Sam’s secret",
    jumble: "public jumble",
    shake: "shake",
    padlock: "Sam’s padlock",
    alexKey: "Alex’s secret key",
    sent: "sent to Sam",
    eve: "Eve sees",
    mess: "just a mess",
    zero: "0",
    one: "1",
    read: "Sam reads",
    same: "same key ✓",
    alex: "Alex",
    sam: "Sam",
    eveName: "Eve",
    url: "any-website.com",
    pushed: "each 1 → 49",
    title: "ML-KEM",
    aria: "The toy ML-KEM: keys, a message on a 97-hour clock, and the shared key",
  },
};

export const scene1 = {
  kicker: "Chapter 1 · Try it yourself",
  title: "Play with the grid",
  paragraphs: [
    "Drag the tips of arrows A and B. The whole grid changes shape.",
    "Click anywhere to drop a ball. The closest dot lights up.",
  ],
  hint: "Drag the arrow tips · Click anywhere to drop a ball",
  labels: {
    basis1: "A",
    basis2: "B",
    nearest: "nearest dot",
    coords: "Show coordinates",
    reset: "Reset arrows",
    degenerate: "The arrows point the same way, so they only make a line. Pull one of them off the line.",
    canvas: "Interactive 2-D lattice",
  },
  readout: {
    found: "The nearest dot lights up. Drag an arrow: the grid changes, and so can the answer.",
    // only shown when “Show coordinates” is on (the scene has no numbers otherwise)
    coords: "Closest dot = {c1} × A {sign} {c2} × B  ·  {dist} away",
  },
};

export const scene2 = {
  kicker: "Chapter 2 · Try it yourself",
  title: "Play with good and bad arrows",
  paragraphs: [
    "Click anywhere on the grid to drop a ball. The finder walks with the current arrows and stops at a dot.",
    "Switch between “Good basis” and “Bad basis”, then press “Throw 20 balls” and compare how often each one misses.",
  ],
  hint: "Press “Bad basis” below · Click anywhere to throw a ball",
  labels: {
    good: "Good basis",
    bad: "Bad basis",
    tallyGood: "Good basis",
    tallyBad: "Bad basis",
    throwMany: "Throw 20 balls",
    clear: "Clear",
    wrong: "wrong",
    rightDot: "found it",
    wrongDot: "missed",
    realDot: "the real nearest dot",
    basis1: "b₁",
    basis2: "b₂",
    canvas: "The same lattice with a good and a bad basis",
    group: "Basis",
  },
  readout: {
    right: "Found the nearest dot, {dist} away.",
    wrong: "Missed. This basis stopped {guess} away, but the nearest dot was {truth} away.",
    throwing: "Throwing… {wrong} of {total} wrong so far",
  },
};

export const scene3 = {
  kicker: "Chapter 3 · Try it yourself",
  title: "Play with the shake",
  paragraphs: [
    "Press “Send 0”, “Send 1” or “Send 20 bits”. Sam (green) and Eve (red) both try to read every ball.",
    "Drag the “Wobble” slider. At zero, Eve reads everything. A little shake blinds her. Too much, and Sam fails too.",
  ],
  hint: "Press “Send 0” or “Send 1” · Drag “Wobble” to change the shake",
  labels: {
    send0: "Send 0",
    send1: "Send 1",
    sendMany: "Send 20 bits",
    wobble: "Wobble",
    clear: "Clear",
    owner: "Sam",
    eaves: "Eve",
    reads: "reads",
    right: "right",
    canvas: "Sending a secret bit through the lattice with a wobble",
  },
  readout: {
    result: "Sent {bit}  ·  Sam read {o}  ·  Eve read {e}",
    sending: "Sending…  Sam {o} right  ·  Eve {e} right",
    zero: "Wobble is zero: the ball sits exactly on a dot or exactly halfway, so anyone can read it.",
    tooMuch: "Too much wobble: the ball can leave the green circle, and then even Sam misreads.",
  },
};

export const scene4 = {
  kicker: "Chapter 4 · Try it yourself",
  title: "Climb the dimensions yourself",
  paragraphs: [
    "Press “3D” or “4D” and drag to spin the grid. Click to drop a ball. In 4D, dots that fade are far away in the fourth direction.",
    "Press “Run the attack” to watch Eve’s weapon tidy the red arrows move by move. Under the grid, pick how many grids to test and how high to climb.",
  ],
  hint: "Press “3D” or “4D” · Click to throw a ball · Press “Run the attack”",
  labels: {
    dims: ["2D", "3D", "4D"],
    run: "Run the attack",
    reset: "Reset arrows",
    loading: "Loading 3D…",
    canvas: "A lattice in 2, 3 or 4 dimensions",
    dimsGroup: "Dimensions",
    failed: "The 3D view could not load (it needs Three.js from the internet). The chart below still works.",
  },
  readout: {
    reduce: "Step {s} of {n}: shorten arrow {i} using arrow {j}",
    swap: "Step {s} of {n}: swap arrows {a} and {b}",
    done: "Done in {n} steps. The arrows are short and square: in {d}D the attacker wins.",
    reset: "Back to the bad basis.",
    ball: "The ball's nearest dot is {dist} away.",
  },
  quantum: {
    title: "Two quantum tricks, two different stories",
    shor: {
      name: "Shor’s algorithm",
      body: "Finds a hidden repeating pattern in numbers. Today’s locks (RSA and elliptic curves) are built on exactly such a pattern, so a big enough quantum computer opens them completely.",
      verdict: "Today’s locks: broken",
    },
    grover: {
      name: "Grover’s algorithm",
      body: "Speeds up blind guessing, but only by a square root: a million guesses become a thousand. A grid has no pattern for Shor to find, and Grover-style searching trims the grid attack only a little.",
      verdict: "Grids: still safe (just make them a bit bigger)",
    },
  },
  chart: {
    title: "Did the attack recover the secret?",
    ratio: "Attacker's shortest arrow ÷ the hidden one",
    found: "1× = found it",
    dimension: "D",
    gaveUp: "gave up (over 2 s)",
    kyber: "Kyber: 512+ →",
    idle: "Press “Run the attack”, or pick a setting below, to fill in the chart.",
    grids: "Grids per dimension",
    climb: "Climb to",
    running: "Attacking {trials} random grids in {d} dimensions…",
    done: "{trials} random grids per dimension. Each attack took under {ms} ms.",
    noWorker: "Running on the main thread (this browser has no module workers).",
  },
};

export const scene5 = {
  kicker: "Chapter 5 · Try it yourself",
  title: "Lock your own message",
  paragraphs: [
    "Type a message in the box. Then press “Make new keys”, “Lock a new key” and “Unlock”, one after another. Every number on screen is real.",
    "Press “show it on the lattice” in any step to see the same step as dots and arrows.",
  ],
  labels: {
    message: "Your message",
    placeholder: "Type a short message",
    keygen: "1 · Make keys",
    encaps: "2 · Lock",
    decaps: "3 · Unlock",
    keygenBtn: "Make new keys",
    encapsBtn: "Lock a new key",
    decapsBtn: "Unlock",
    show: "show it on the lattice",
    A: "A (public jumble)",
    s: "s (secret)",
    e: "e (wobble)",
    t: "t = A·s + e (public)",
    m: "8 random bits",
    u: "u (ciphertext)",
    v: "v (ciphertext)",
    key: "shared key",
    sealed: "locked message",
    diff: "v − s·u (on the 97-hour clock)",
    bits: "bits read",
    opened: "unlocked message",
    waitEncaps: "Press “Lock a new key”.",
    waitDecaps: "Press “Unlock”.",
    match: "same key as the sender ✓",
    noMatch: "different key ✗",
    zero: "0",
    one: "1",
  },
  scale: {
    title: "For scale",
    intro: "The toy on this page next to ML-KEM-768, the size your browser uses.",
    toy: "Toy",
    real: "ML-KEM-768",
    bytes: "bytes",
    rows: { publicKey: "Public key", ciphertext: "Ciphertext", sharedKey: "Shared key" },
    note: "Real ML-KEM sends a short seed instead of the whole jumble A, and squeezes the ciphertext. The shared key is the same size: 32 bytes.",
  },
  lattice: {
    canvas: "The current step drawn on the lattice",
    lockedDot: "A·s",
    lockedBall: "t = A·s + e",
    keygen: "Keys: the green arrows are the secret key, the red ones are the public key. Same grid.",
    encaps: "Lock: each bit is a ball. 0 sits on a dot, 1 is pushed half a step, then everything wobbles.",
    decaps: "Unlock: Sam rounds each ball with the green arrows and reads the leftover.",
  },
};
